/*
 * This file is generated by jOOQ.
 */
package com.github.vti.amcrm.db;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import com.github.vti.amcrm.db.tables.Customer;
import com.github.vti.amcrm.db.tables.Event;
import com.github.vti.amcrm.db.tables.records.CustomerRecord;
import com.github.vti.amcrm.db.tables.records.EventRecord;

/** A class modelling foreign key relationships and constraints of tables in the default schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> PK_CUSTOMER =
            Internal.createUniqueKey(
                    Customer.CUSTOMER,
                    DSL.name("pk_customer"),
                    new TableField[] {Customer.CUSTOMER.ID},
                    true);
    public static final UniqueKey<EventRecord> PK_EVENT =
            Internal.createUniqueKey(
                    Event.EVENT, DSL.name("pk_event"), new TableField[] {Event.EVENT.ID}, true);
}
