/*
 * This file is generated by jOOQ.
 */
package com.github.vti.amcrm.db;

import com.github.vti.amcrm.db.tables.Customer;

/** Convenience access to all tables in the default schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /** The table <code>customer</code>. */
    public static final Customer CUSTOMER = Customer.CUSTOMER;
}
