/*
 * This file is generated by jOOQ.
 */
package com.github.vti.amcrm.db.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import com.github.vti.amcrm.db.tables.Event;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventRecord extends UpdatableRecordImpl<EventRecord>
        implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /** Setter for <code>event.id</code>. */
    public void setId(Integer value) {
        set(0, value);
    }

    /** Getter for <code>event.id</code>. */
    public Integer getId() {
        return (Integer) get(0);
    }

    /** Setter for <code>event.name</code>. */
    public void setName(String value) {
        set(1, value);
    }

    /** Getter for <code>event.name</code>. */
    public String getName() {
        return (String) get(1);
    }

    /** Setter for <code>event.origin_id</code>. */
    public void setOriginId(String value) {
        set(2, value);
    }

    /** Getter for <code>event.origin_id</code>. */
    public String getOriginId() {
        return (String) get(2);
    }

    /** Setter for <code>event.user_id</code>. */
    public void setUserId(String value) {
        set(3, value);
    }

    /** Getter for <code>event.user_id</code>. */
    public String getUserId() {
        return (String) get(3);
    }

    /** Setter for <code>event.payload</code>. */
    public void setPayload(String value) {
        set(4, value);
    }

    /** Getter for <code>event.payload</code>. */
    public String getPayload() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Event.EVENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Event.EVENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Event.EVENT.ORIGIN_ID;
    }

    @Override
    public Field<String> field4() {
        return Event.EVENT.USER_ID;
    }

    @Override
    public Field<String> field5() {
        return Event.EVENT.PAYLOAD;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getOriginId();
    }

    @Override
    public String component4() {
        return getUserId();
    }

    @Override
    public String component5() {
        return getPayload();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getOriginId();
    }

    @Override
    public String value4() {
        return getUserId();
    }

    @Override
    public String value5() {
        return getPayload();
    }

    @Override
    public EventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EventRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public EventRecord value3(String value) {
        setOriginId(value);
        return this;
    }

    @Override
    public EventRecord value4(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public EventRecord value5(String value) {
        setPayload(value);
        return this;
    }

    @Override
    public EventRecord values(
            Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Create a detached EventRecord */
    public EventRecord() {
        super(Event.EVENT);
    }

    /** Create a detached, initialised EventRecord */
    public EventRecord(Integer id, String name, String originId, String userId, String payload) {
        super(Event.EVENT);

        setId(id);
        setName(name);
        setOriginId(originId);
        setUserId(userId);
        setPayload(payload);
    }
}
