/*
 * This file is generated by jOOQ.
 */
package com.github.vti.amcrm.db.tables.records;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import com.github.vti.amcrm.db.tables.User;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRecord extends UpdatableRecordImpl<UserRecord>
        implements Record10<
                String,
                Long,
                String,
                Boolean,
                LocalDateTime,
                String,
                LocalDateTime,
                String,
                LocalDateTime,
                String> {

    private static final long serialVersionUID = 1L;

    /** Setter for <code>user.id</code>. */
    public void setId(String value) {
        set(0, value);
    }

    /** Getter for <code>user.id</code>. */
    public String getId() {
        return (String) get(0);
    }

    /** Setter for <code>user.version</code>. */
    public void setVersion(Long value) {
        set(1, value);
    }

    /** Getter for <code>user.version</code>. */
    public Long getVersion() {
        return (Long) get(1);
    }

    /** Setter for <code>user.name</code>. */
    public void setName(String value) {
        set(2, value);
    }

    /** Getter for <code>user.name</code>. */
    public String getName() {
        return (String) get(2);
    }

    /** Setter for <code>user.is_admin</code>. */
    public void setIsAdmin(Boolean value) {
        set(3, value);
    }

    /** Getter for <code>user.is_admin</code>. */
    public Boolean getIsAdmin() {
        return (Boolean) get(3);
    }

    /** Setter for <code>user.created_at</code>. */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /** Getter for <code>user.created_at</code>. */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /** Setter for <code>user.created_by</code>. */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /** Getter for <code>user.created_by</code>. */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /** Setter for <code>user.updated_at</code>. */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /** Getter for <code>user.updated_at</code>. */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /** Setter for <code>user.updated_by</code>. */
    public void setUpdatedBy(String value) {
        set(7, value);
    }

    /** Getter for <code>user.updated_by</code>. */
    public String getUpdatedBy() {
        return (String) get(7);
    }

    /** Setter for <code>user.deleted_at</code>. */
    public void setDeletedAt(LocalDateTime value) {
        set(8, value);
    }

    /** Getter for <code>user.deleted_at</code>. */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(8);
    }

    /** Setter for <code>user.deleted_by</code>. */
    public void setDeletedBy(String value) {
        set(9, value);
    }

    /** Getter for <code>user.deleted_by</code>. */
    public String getDeletedBy() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<
                    String,
                    Long,
                    String,
                    Boolean,
                    LocalDateTime,
                    String,
                    LocalDateTime,
                    String,
                    LocalDateTime,
                    String>
            fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<
                    String,
                    Long,
                    String,
                    Boolean,
                    LocalDateTime,
                    String,
                    LocalDateTime,
                    String,
                    LocalDateTime,
                    String>
            valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<Long> field2() {
        return User.USER.VERSION;
    }

    @Override
    public Field<String> field3() {
        return User.USER.NAME;
    }

    @Override
    public Field<Boolean> field4() {
        return User.USER.IS_ADMIN;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return User.USER.CREATED_AT;
    }

    @Override
    public Field<String> field6() {
        return User.USER.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.UPDATED_AT;
    }

    @Override
    public Field<String> field8() {
        return User.USER.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return User.USER.DELETED_AT;
    }

    @Override
    public Field<String> field10() {
        return User.USER.DELETED_BY;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Boolean component4() {
        return getIsAdmin();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public String component6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public String component8() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getDeletedAt();
    }

    @Override
    public String component10() {
        return getDeletedBy();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Boolean value4() {
        return getIsAdmin();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public String value6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public String value8() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getDeletedAt();
    }

    @Override
    public String value10() {
        return getDeletedBy();
    }

    @Override
    public UserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value4(Boolean value) {
        setIsAdmin(value);
        return this;
    }

    @Override
    public UserRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public UserRecord value9(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setDeletedBy(value);
        return this;
    }

    @Override
    public UserRecord values(
            String value1,
            Long value2,
            String value3,
            Boolean value4,
            LocalDateTime value5,
            String value6,
            LocalDateTime value7,
            String value8,
            LocalDateTime value9,
            String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Create a detached UserRecord */
    public UserRecord() {
        super(User.USER);
    }

    /** Create a detached, initialised UserRecord */
    public UserRecord(
            String id,
            Long version,
            String name,
            Boolean isAdmin,
            LocalDateTime createdAt,
            String createdBy,
            LocalDateTime updatedAt,
            String updatedBy,
            LocalDateTime deletedAt,
            String deletedBy) {
        super(User.USER);

        setId(id);
        setVersion(version);
        setName(name);
        setIsAdmin(isAdmin);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setDeletedAt(deletedAt);
        setDeletedBy(deletedBy);
    }
}
